<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-I2FKUVF" ignored="0" name="Add Customer Test" tests="2" failures="2" timestamp="19 Aug 2018 05:39:16 GMT" time="1.734" errors="0">
  <testcase name="addCustomer" time="0.652" classname="com.ddf.testcases.AddCustomer">
    <failure type="java.lang.AssertionError" message="customer not added sucessfully">
      <![CDATA[java.lang.AssertionError: customer not added sucessfully
at com.ddf.testcases.AddCustomer.addCustomer(AddCustomer.java:26)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- addCustomer -->
  <testcase name="addCustomer" time="0.303" classname="com.ddf.testcases.AddCustomer">
    <failure type="java.lang.AssertionError" message="customer not added sucessfully">
      <![CDATA[java.lang.AssertionError: customer not added sucessfully
at com.ddf.testcases.AddCustomer.addCustomer(AddCustomer.java:26)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- addCustomer -->
</testsuite> <!-- Add Customer Test -->
